using System.Collections;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using MahApps.Metro.Controls;

namespace CarSystem.App.Windows
{
	public partial class GenericListWindow : MetroWindow
	{
		public GenericListWindow(string title, IList items)
		{
			WindowTransitionsEnabled = false;
			InitializeComponent();
			WindowTitleBlock.Text = title.ToUpper();
			Title = title;
			GenericDataGrid.AutoGeneratedColumns += GenericDataGrid_AutoGeneratedColumns;
			GenericDataGrid.ItemsSource = items;
		}

		private void GenericDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
		{
			if (e.PropertyDescriptor is PropertyDescriptor descriptor)
			{
				if (!descriptor.IsBrowsable)
				{
					e.Cancel = true;
					return;
				}
				e.Column.Header = descriptor.DisplayName ?? descriptor.Name;
			}
		}

		private void GenericDataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
		{
			ColumnChooserList.Items.Clear();
			foreach (var column in GenericDataGrid.Columns)
			{
				var cb = new CheckBox
				{
					Content = column.Header?.ToString(),
					IsChecked = column.Visibility == Visibility.Visible,
					Margin = new Thickness(0, 3, 0, 3),
					Tag = column
				};
				cb.Checked += (s, e2) => ((DataGridColumn)((CheckBox)s).Tag).Visibility = Visibility.Visible;
				cb.Unchecked += (s, e2) => ((DataGridColumn)((CheckBox)s).Tag).Visibility = Visibility.Collapsed;
				ColumnChooserList.Items.Add(cb);
			}
		}

		private void ColumnChooserButton_Click(object sender, RoutedEventArgs e)
		{
			ColumnChooserPopup.IsOpen = !ColumnChooserPopup.IsOpen;
		}

		private void CloseButton_Click(object sender, RoutedEventArgs e)
		{
			this.Close();
		}
	}
}
