using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Autofac;
using CarSystem.App.Infrastructure;
using CarSystem.App.Infrastructure.Helpers;
using CarSystem.ViewModels;
using CarSystem.App.Windows.Forms;
using CarSystem.Data.Models.Associative;
using CarSystem.Services.Contracts;
using MahApps.Metro.Controls;
using MahApps.Metro.Controls.Dialogs;

namespace CarSystem.App.Windows
{
	public partial class Violations : MetroWindow
	{
		Autofac.IContainer container = ContainerConfiguration.GetContainer();

		private readonly IPersonFinesService _personFinesService;
		private readonly IViolationService _violationService;

		public BulkObservableCollection<ViolationsViewModel> ViolationsViewModels { get; set; }
		public BulkObservableCollection<ViolationViewModel> ViolationsViewModel { get; set; }

		public Violations()
		{
			WindowTransitionsEnabled = false;
			_personFinesService = container.Resolve<IPersonFinesService>();
			_violationService = container.Resolve<IViolationService>();

			ViolationsViewModels = new BulkObservableCollection<ViolationsViewModel>();
			ViolationsViewModel = new BulkObservableCollection<ViolationViewModel>();
			InitializeComponent();
			ViolationsDataGrid.AutoGeneratedColumns += ViolationsDataGrid_AutoGeneratedColumns;
			ViolationsDataGrid.ItemsSource = ViolationsViewModels;
			ViolationPickerButton.ItemsSource = ViolationsViewModel;
			Loaded += OnLoaded;
		}

		private void OnLoaded(object sender, RoutedEventArgs e)
		{
			LoadViolationsViewModels();
			LoadViolationsViewModel();
		}

		private async void LoadViolationsViewModels()
		{
			var dbRecords = await _personFinesService.GetFilteredPersonFinesAsync();
			var observableDtoModels = ModelHandler.PersonFinesToObservableDto(dbRecords);
			ModelHandler.ProcessObservableDtoModels(ViolationsViewModels, observableDtoModels);
		}

		private async void LoadViolationsViewModel()
		{
			var dbRecords = await _violationService.GetAllViolationsAsync();
			var observableDtoModels = ModelHandler.ViolationsToObservableDto(dbRecords);
			ModelHandler.ProcessObservableDtoModels(ViolationsViewModel, observableDtoModels);
		}

		private void PreviousButton_Click(object sender, RoutedEventArgs e)
		{
			var myMenu = container.Resolve<MyMenu>();
			myMenu.Show();
			this.Close();
		}

		private void HomeScreenButton_Click(object sender, RoutedEventArgs e)
		{
			var startupWindow = container.Resolve<MainWindow>();
			startupWindow.Show();
			this.Close();
		}

		private async void FilterButton_Click(object sender, RoutedEventArgs e)
		{
			var violationName = (ViolationPickerButton.SelectedItem as ViolationViewModel)?.Name ?? string.Empty;
			var dbRecords = await _personFinesService.GetFilteredPersonFinesAsync(violationName, CardIdTextBox.Text, EGNTextBox.Text, VehicleNumberTextBox.Text, FineNumberTextBox.Text);
			var observableDtoModels = ModelHandler.PersonFinesToObservableDto(dbRecords);
			ModelHandler.ProcessObservableDtoModels(ViolationsViewModels, observableDtoModels);
		}

		private void ClearFiltersButton_Click(object sender, RoutedEventArgs e)
		{
			CardIdTextBox.Text = "";
			FineNumberTextBox.Text = "";
			EGNTextBox.Text = "";
			VehicleNumberTextBox.Text = "";
			ViolationPickerButton.SelectedItem = null;
			FilterButton.IsEnabled = false;

			LoadViolationsViewModels();
		}

		private void UpdateFilterButtonState()
		{
			FilterButton.IsEnabled = !string.IsNullOrEmpty(CardIdTextBox.Text)
				|| !string.IsNullOrEmpty(FineNumberTextBox.Text)
				|| !string.IsNullOrEmpty(EGNTextBox.Text)
				|| !string.IsNullOrEmpty(VehicleNumberTextBox.Text)
				|| ViolationPickerButton.SelectedItem != null;
		}

		private void TextBoxChange(object sender, TextChangedEventArgs e)
		{
			UpdateFilterButtonState();
		}

		// Use DisplayName property to visualize column names and make text centered
		private void ViolationsDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
		{
			if (e.PropertyDescriptor is PropertyDescriptor descriptor)
			{
				e.Column.Header = descriptor.DisplayName ?? descriptor.Name;
				//e.Column.HeaderStyle = new Style(typeof(DataGridColumnHeader));
				//e.Column.HeaderStyle.Setters.Add(new Setter(HorizontalContentAlignmentProperty, HorizontalAlignment.Center));
			}
		}

		private void ViolationsDataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
		{
			ViolationColumnChooserList.Items.Clear();
			foreach (var column in ViolationsDataGrid.Columns)
			{
				var cb = new CheckBox
				{
					Content = column.Header?.ToString(),
					IsChecked = column.Visibility == Visibility.Visible,
					Margin = new Thickness(0, 3, 0, 3),
					Tag = column
				};
				cb.Checked += (s, e2) => ((DataGridColumn)((CheckBox)s).Tag).Visibility = Visibility.Visible;
				cb.Unchecked += (s, e2) => ((DataGridColumn)((CheckBox)s).Tag).Visibility = Visibility.Collapsed;
				ViolationColumnChooserList.Items.Add(cb);
			}
		}

		private void ViolationColumnChooserButton_Click(object sender, RoutedEventArgs e)
		{
			ViolationColumnChooserPopup.IsOpen = !ViolationColumnChooserPopup.IsOpen;
		}

		private void HamburgerMenuButton_Click(object sender, RoutedEventArgs e)
		{
			HamburgerMenuFlyout.IsOpen = true;
		}

		private void CreateButton_Click(object sender, RoutedEventArgs e)
		{
			var myMenu = container.Resolve<CreateViolation>();
			
			myMenu.ShowDialog();
		}

		private async void DeleteItem_Click(object sender, RoutedEventArgs e)
		{
			var rowData = ViolationsDataGrid.SelectedItem as ViolationsViewModel;
			this.Cursor = Cursors.Hand;
			var result = await this.ShowMessageAsync("Сигурни ли сте?", "Записът ще бъде изтрит от системата!", MessageDialogStyle.AffirmativeAndNegative, MetroDialogOptions = new MetroDialogSettings()
			{
				AffirmativeButtonText = "Да",
				AnimateHide = true,
				AnimateShow = true,
				NegativeButtonText = "Не",
				DefaultButtonFocus = MessageDialogResult.Affirmative,
				DialogResultOnCancel = MessageDialogResult.Canceled,
			});

			if (result == MessageDialogResult.Affirmative)
			{
				await _personFinesService.DeletePersonFineAsync(rowData.PersonFineId);
				ViolationsViewModels.Remove(rowData);
			}
			this.Cursor = Cursors.Arrow;
		}

		// Disable contextMenu in data grid headers
		private void DisableContextMenuOnDgHeaders_PreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
		{
			DependencyObject DepObject = (DependencyObject)e.OriginalSource;

			while ((DepObject != null) && !(DepObject is DataGridColumnHeader) && !(DepObject is DataGridRow))
			{
				DepObject = VisualTreeHelper.GetParent(DepObject);
			}

			if (DepObject == null)
			{
				return;
			}

			if (DepObject is DataGridColumnHeader)
			{
				ViolationsDataGrid.ContextMenu.Visibility = Visibility.Collapsed;
			}
			else
			{
				ViolationsDataGrid.ContextMenu.Visibility = Visibility.Visible;
			}
		}

		private void ViolationPickerButton_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			UpdateFilterButtonState();
		}
	}
}
